In [21]:
import pandas as pd

In [22]:
import requests

In [23]:
response = requests.get('https://api.themoviedb.org/3/tv/top_rated?api_key=40ce6d2d68786e189606e98b6c89eb07&language=en-US')

Process of Fetching API Data in Python
The process shown in your notebook fetches data from a web server (TMDB API) into Python using the requests library in four main steps:

Importing the Library: import requests loads Python's built-in tool for making HTTP network calls.

Sending an HTTP GET Request: requests.get('URL') sends a request to the server at the specified URL endpoint, passing query parameters such as your api_key and language.

Receiving the Response: The server processes the request and sends back a response object containing a Status Code (e.g., <Response [200]>), response headers, and raw payload data.

Parsing the Data: By default, requests.get() returns a response object rather than the raw data. To read the returned dataset in JSON format, save the response to a variable and call the .json() method:

Python

Common HTTP Status Codes
HTTP status codes are three-digit numbers sent by a server to indicate the status of a request:

2xx Success (Request succeeded)
200 OK: The request was successful, and the requested data was returned.

201 Created: The request succeeded and resulted in a new resource being created (common for POST requests).

204 No Content: The request succeeded, but there is no payload returned in the response body.

4xx Client Errors (Issue with the request sent)
400 Bad Request: The server could not understand the request due to invalid syntax or missing required parameters.

401 Unauthorized: Authentication failed or was not provided (e.g., missing or invalid api_key).

403 Forbidden: You are authenticated, but you do not have permission to access the requested resource.

404 Not Found: The endpoint URL or requested resource does not exist on the server.

429 Too Many Requests: You have exceeded the rate limit (sent too many requests in a given time frame).

5xx Server Errors (Issue on the provider's server)
500 Internal Server Error: The server encountered an unexpected error while processing the request.

502 Bad Gateway: The server received an invalid response from an upstream server.

503 Service Unavailable: The server is temporarily overloaded or down for maintenance.

In [24]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
   'genre_ids': [10759, 18, 35],
   'id': 276161,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '참교육',
   'overview': 'An inspector from the Educational Rights Protection Bureau (ERPB) who is authorized by the government to use physical intervention and unconventional methods to discipline delinquent students and reform the educational system.',
   'popularity': 72.1513,
   'poster_path': '/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
   'first_air_date': '2026-06-05',
   'softcore': False,
   'name': 'Teach You a Lesson',
   'vote_average': 9.419,
   'vote_count': 788},
  {'adult': False,
   'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
   'genre_ids': [37, 18],
   'id': 299167,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Dutton Ranch',
   'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
   'popularity': 67.3828,
   'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
   'first_air_date': '2026-05-15',
   'softcore': False,
   'name': 'Dutton Ranch',
   'vote_average': 9.175,
   'vote_count': 512},
  {'adult': False,
   'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
   'genre_ids': [18, 80],
   'id': 1396,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Breaking Bad',
   'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
   'popularity': 147.6765,
   'poster_path': '/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg',
   'first_air_date': '2008-01-20',
   'softcore': False,
   'name': 'Breaking Bad',
   'vote_average': 8.947,
   'vote_count': 18346},
  {'adult': False,
   'backdrop_path': '/TGJ34SvYJ2ZgzsOgAaXzSx3o7E.jpg',
   'genre_ids': [18],
   'id': 273240,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Off Campus',
   'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
   'popularity': 91.7782,
   'poster_path': '/tcPc5ZMBO4y2BtCJMe3o2nwZb2B.jpg',
   'first_air_date': '2026-05-13',
   'softcore': False,
   'name': 'Off Campus',
   'vote_average': 8.914,
   'vote_count': 772},
  {'adult': False,
   'backdrop_path': '/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg',
   'genre_ids': [10759, 35, 10765, 18],
   'id': 259837,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '원더풀스',
   'overview': 'A goofy group of townies stumbles into superpowers and fights rising evil as doomsday panic grows in this wild, turn-of-the-century action comedy.',
   'popularity': 24.6367,
   'poster_path': '/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg',
   'first_air_date': '2026-05-15',
   'softcore': False,
   'name': 'The WONDERfools',
   'vote_average': 8.9,
   'vote_count': 241},
  {'adult': False,
   'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
   'genre_ids': [16, 10759, 18, 10765],
   'id': 209867,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '葬送のフリーレン',
   'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
   'popularity': 85.9744,
   'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
   'first_air_date': '2023-09-29',
   'softcore': False,
   'name': "Frieren: Beyond Journey's End",
   'vote_average': 8.8,
   'vote_count': 918},
  {'adult': False,
   'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
   'genre_ids': [10759, 10751, 18],
   'id': 85077,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Chosen',
   'overview': 'The life of Christ through the eyes of those who encountered him.',
   'popularity': 74.8496,
   'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
   'first_air_date': '2019-04-21',
   'softcore': False,
   'name': 'The Chosen',
   'vote_average': 8.783,
   'vote_count': 943},
  {'adult': False,
   'backdrop_path': '/kU98MbVVgi72wzceyrEbClZmMFe.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 246,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Avatar: The Last Airbender',
   'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
   'popularity': 34.2859,
   'poster_path': '/yaGt4GIutpbXHsv48tWceWg6s56.jpg',
   'first_air_date': '2005-02-21',
   'softcore': False,
   'name': 'Avatar: The Last Airbender',
   'vote_average': 8.776,
   'vote_count': 5031},
  {'adult': False,
   'backdrop_path': '/wgmikRStgBbrzjxFVe5rhFlpL2R.jpg',
   'genre_ids': [35],
   'id': 64010,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '응답하라 1988',
   'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
   'popularity': 16.1474,
   'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
   'first_air_date': '2015-11-06',
   'softcore': False,
   'name': 'Reply 1988',
   'vote_average': 8.8,
   'vote_count': 221},
  {'adult': False,
   'backdrop_path': '/a9qlroMOHewiDsUR93PYMVfpbF5.jpg',
   'genre_ids': [18],
   'id': 219246,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '폭싹 속았수다',
   'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
   'popularity': 26.3361,
   'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
   'first_air_date': '2025-03-07',
   'softcore': False,
   'name': 'When Life Gives You Tangerines',
   'vote_average': 8.759,
   'vote_count': 565},
  {'adult': False,
   'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 94605,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Arcane',
   'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
   'popularity': 35.5446,
   'poster_path': '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
   'first_air_date': '2021-11-06',
   'softcore': False,
   'name': 'Arcane',
   'vote_average': 8.752,
   'vote_count': 6090},
  {'adult': False,
   'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
   'genre_ids': [10759, 35, 16],
   'id': 37854,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ワンピース',
   'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
   'popularity': 50.237,
   'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
   'first_air_date': '1999-10-20',
   'softcore': False,
   'name': 'One Piece',
   'vote_average': 8.752,
   'vote_count': 5474},
  {'adult': False,
   'backdrop_path': '/iS76c29IrS3lKI2X5CFySguiAWU.jpg',
   'genre_ids': [18],
   'id': 301507,
   'origin_country': ['CA'],
   'original_language': 'en',
   'original_name': 'Heated Rivalry',
   'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
   'popularity': 31.6016,
   'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
   'first_air_date': '2025-11-28',
   'softcore': False,
   'name': 'Heated Rivalry',
   'vote_average': 8.75,
   'vote_count': 570},
  {'adult': False,
   'backdrop_path': '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
   'genre_ids': [18],
   'id': 250307,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Pitt',
   'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
   'popularity': 90.0029,
   'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
   'first_air_date': '2025-01-09',
   'softcore': False,
   'name': 'The Pitt',
   'vote_average': 8.727,
   'vote_count': 890},
  {'adult': False,
   'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
   'genre_ids': [18],
   'id': 87108,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Chernobyl',
   'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
   'popularity': 37.6323,
   'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
   'first_air_date': '2019-05-06',
   'softcore': False,
   'name': 'Chernobyl',
   'vote_average': 8.722,
   'vote_count': 8143},
  {'adult': False,
   'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
   'genre_ids': [16, 10759, 10765, 18],
   'id': 31911,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
   'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
   'popularity': 47.3033,
   'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
   'first_air_date': '2009-04-05',
   'softcore': False,
   'name': 'Fullmetal Alchemist: Brotherhood',
   'vote_average': 8.7,
   'vote_count': 2533},
  {'adult': False,
   'backdrop_path': '/rfxryDIv8huejujg4JueDJx8zCz.jpg',
   'genre_ids': [80, 18],
   'id': 60059,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Better Call Saul',
   'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
   'popularity': 74.8616,
   'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
   'first_air_date': '2015-02-08',
   'softcore': False,
   'name': 'Better Call Saul',
   'vote_average': 8.711,
   'vote_count': 6739},
  {'adult': False,
   'backdrop_path': '/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg',
   'genre_ids': [18, 35],
   'id': 259666,
   'origin_country': ['MX'],
   'original_language': 'es',
   'original_name': 'Nadie nos va a extrañar',
   'overview': "It's the '90s, and five losers run an illegal business at their high school. They sell homework and assignments to their classmates. The advantage is that no one ever suspects the nerds. Their business brings them money and popularity. But hormones and an unexpected death threaten to ruin everything. If the business collapses, their futures and their friendships are at risk.",
   'popularity': 41.9727,
   'poster_path': '/5U3WiAz67fJn5gnvFk4zOJAx9Sc.jpg',
   'first_air_date': '2024-08-09',
   'softcore': False,
   'name': 'No One Will Miss Us',
   'vote_average': 8.709,
   'vote_count': 340},
  {'adult': False,
   'backdrop_path': '/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
   'genre_ids': [10759, 18],
   'id': 200709,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '약한영웅',
   'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
   'popularity': 49.3876,
   'poster_path': '/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
   'first_air_date': '2022-11-18',
   'softcore': False,
   'name': 'Weak Hero',
   'vote_average': 8.699,
   'vote_count': 502},
  {'adult': False,
   'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
   'genre_ids': [16, 10765, 10759],
   'id': 1429,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '進撃の巨人',
   'overview': '100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
   'popularity': 31.3241,
   'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
   'first_air_date': '2013-04-07',
   'softcore': False,
   'name': 'Attack on Titan',
   'vote_average': 8.684,
   'vote_count': 7610}],
 'total_pages': 126,
 'total_results': 2514}

In [25]:
 #to get this in list format
 response.json()['results']

[{'adult': False,
  'backdrop_path': '/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
  'genre_ids': [10759, 18, 35],
  'id': 276161,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '참교육',
  'overview': 'An inspector from the Educational Rights Protection Bureau (ERPB) who is authorized by the government to use physical intervention and unconventional methods to discipline delinquent students and reform the educational system.',
  'popularity': 72.1513,
  'poster_path': '/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
  'first_air_date': '2026-06-05',
  'softcore': False,
  'name': 'Teach You a Lesson',
  'vote_average': 9.419,
  'vote_count': 788},
 {'adult': False,
  'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
  'genre_ids': [37, 18],
  'id': 299167,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Dutton Ranch',
  'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
  'popularity': 67.3828,
  'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
  'first_air_date': '2026-05-15',
  'softcore': False,
  'name': 'Dutton Ranch',
  'vote_average': 9.175,
  'vote_count': 512},
 {'adult': False,
  'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
  'genre_ids': [18, 80],
  'id': 1396,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Breaking Bad',
  'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
  'popularity': 147.6765,
  'poster_path': '/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg',
  'first_air_date': '2008-01-20',
  'softcore': False,
  'name': 'Breaking Bad',
  'vote_average': 8.947,
  'vote_count': 18346},
 {'adult': False,
  'backdrop_path': '/TGJ34SvYJ2ZgzsOgAaXzSx3o7E.jpg',
  'genre_ids': [18],
  'id': 273240,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Off Campus',
  'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
  'popularity': 91.7782,
  'poster_path': '/tcPc5ZMBO4y2BtCJMe3o2nwZb2B.jpg',
  'first_air_date': '2026-05-13',
  'softcore': False,
  'name': 'Off Campus',
  'vote_average': 8.914,
  'vote_count': 772},
 {'adult': False,
  'backdrop_path': '/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg',
  'genre_ids': [10759, 35, 10765, 18],
  'id': 259837,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '원더풀스',
  'overview': 'A goofy group of townies stumbles into superpowers and fights rising evil as doomsday panic grows in this wild, turn-of-the-century action comedy.',
  'popularity': 24.6367,
  'poster_path': '/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg',
  'first_air_date': '2026-05-15',
  'softcore': False,
  'name': 'The WONDERfools',
  'vote_average': 8.9,
  'vote_count': 241},
 {'adult': False,
  'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
  'genre_ids': [16, 10759, 18, 10765],
  'id': 209867,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '葬送のフリーレン',
  'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
  'popularity': 85.9744,
  'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
  'first_air_date': '2023-09-29',
  'softcore': False,
  'name': "Frieren: Beyond Journey's End",
  'vote_average': 8.8,
  'vote_count': 918},
 {'adult': False,
  'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
  'genre_ids': [10759, 10751, 18],
  'id': 85077,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Chosen',
  'overview': 'The life of Christ through the eyes of those who encountered him.',
  'popularity': 74.8496,
  'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
  'first_air_date': '2019-04-21',
  'softcore': False,
  'name': 'The Chosen',
  'vote_average': 8.783,
  'vote_count': 943},
 {'adult': False,
  'backdrop_path': '/kU98MbVVgi72wzceyrEbClZmMFe.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 246,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Avatar: The Last Airbender',
  'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
  'popularity': 34.2859,
  'poster_path': '/yaGt4GIutpbXHsv48tWceWg6s56.jpg',
  'first_air_date': '2005-02-21',
  'softcore': False,
  'name': 'Avatar: The Last Airbender',
  'vote_average': 8.776,
  'vote_count': 5031},
 {'adult': False,
  'backdrop_path': '/wgmikRStgBbrzjxFVe5rhFlpL2R.jpg',
  'genre_ids': [35],
  'id': 64010,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '응답하라 1988',
  'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
  'popularity': 16.1474,
  'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
  'first_air_date': '2015-11-06',
  'softcore': False,
  'name': 'Reply 1988',
  'vote_average': 8.8,
  'vote_count': 221},
 {'adult': False,
  'backdrop_path': '/a9qlroMOHewiDsUR93PYMVfpbF5.jpg',
  'genre_ids': [18],
  'id': 219246,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '폭싹 속았수다',
  'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
  'popularity': 26.3361,
  'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
  'first_air_date': '2025-03-07',
  'softcore': False,
  'name': 'When Life Gives You Tangerines',
  'vote_average': 8.759,
  'vote_count': 565},
 {'adult': False,
  'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 94605,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Arcane',
  'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
  'popularity': 35.5446,
  'poster_path': '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
  'first_air_date': '2021-11-06',
  'softcore': False,
  'name': 'Arcane',
  'vote_average': 8.752,
  'vote_count': 6090},
 {'adult': False,
  'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
  'genre_ids': [10759, 35, 16],
  'id': 37854,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': 'ワンピース',
  'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
  'popularity': 50.237,
  'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
  'first_air_date': '1999-10-20',
  'softcore': False,
  'name': 'One Piece',
  'vote_average': 8.752,
  'vote_count': 5474},
 {'adult': False,
  'backdrop_path': '/iS76c29IrS3lKI2X5CFySguiAWU.jpg',
  'genre_ids': [18],
  'id': 301507,
  'origin_country': ['CA'],
  'original_language': 'en',
  'original_name': 'Heated Rivalry',
  'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
  'popularity': 31.6016,
  'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
  'first_air_date': '2025-11-28',
  'softcore': False,
  'name': 'Heated Rivalry',
  'vote_average': 8.75,
  'vote_count': 570},
 {'adult': False,
  'backdrop_path': '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
  'genre_ids': [18],
  'id': 250307,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Pitt',
  'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
  'popularity': 90.0029,
  'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
  'first_air_date': '2025-01-09',
  'softcore': False,
  'name': 'The Pitt',
  'vote_average': 8.727,
  'vote_count': 890},
 {'adult': False,
  'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
  'genre_ids': [18],
  'id': 87108,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Chernobyl',
  'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
  'popularity': 37.6323,
  'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
  'first_air_date': '2019-05-06',
  'softcore': False,
  'name': 'Chernobyl',
  'vote_average': 8.722,
  'vote_count': 8143},
 {'adult': False,
  'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
  'genre_ids': [16, 10759, 10765, 18],
  'id': 31911,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
  'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
  'popularity': 47.3033,
  'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
  'first_air_date': '2009-04-05',
  'softcore': False,
  'name': 'Fullmetal Alchemist: Brotherhood',
  'vote_average': 8.7,
  'vote_count': 2533},
 {'adult': False,
  'backdrop_path': '/rfxryDIv8huejujg4JueDJx8zCz.jpg',
  'genre_ids': [80, 18],
  'id': 60059,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Better Call Saul',
  'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
  'popularity': 74.8616,
  'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
  'first_air_date': '2015-02-08',
  'softcore': False,
  'name': 'Better Call Saul',
  'vote_average': 8.711,
  'vote_count': 6739},
 {'adult': False,
  'backdrop_path': '/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg',
  'genre_ids': [18, 35],
  'id': 259666,
  'origin_country': ['MX'],
  'original_language': 'es',
  'original_name': 'Nadie nos va a extrañar',
  'overview': "It's the '90s, and five losers run an illegal business at their high school. They sell homework and assignments to their classmates. The advantage is that no one ever suspects the nerds. Their business brings them money and popularity. But hormones and an unexpected death threaten to ruin everything. If the business collapses, their futures and their friendships are at risk.",
  'popularity': 41.9727,
  'poster_path': '/5U3WiAz67fJn5gnvFk4zOJAx9Sc.jpg',
  'first_air_date': '2024-08-09',
  'softcore': False,
  'name': 'No One Will Miss Us',
  'vote_average': 8.709,
  'vote_count': 340},
 {'adult': False,
  'backdrop_path': '/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
  'genre_ids': [10759, 18],
  'id': 200709,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '약한영웅',
  'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
  'popularity': 49.3876,
  'poster_path': '/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
  'first_air_date': '2022-11-18',
  'softcore': False,
  'name': 'Weak Hero',
  'vote_average': 8.699,
  'vote_count': 502},
 {'adult': False,
  'backdrop_path': '/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg',
  'genre_ids': [16, 10765, 10759],
  'id': 1429,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '進撃の巨人',
  'overview': '100 years ago, the last remnants of humanity were forced to retreat behind the towering walls of a fortified city to escape the massive, man-eating Titans that roamed the land outside their fortress. Only the members of the Scouting Legion dared to stray beyond the safety of the walls – but even those brave warriors seldom returned alive. Those within the city clung to the illusion of a peaceful existence until the day that dream was shattered, and their slim chance at survival was reduced to one horrifying choice: kill – or be devoured!',
  'popularity': 31.3241,
  'poster_path': '/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
  'first_air_date': '2013-04-07',
  'softcore': False,
  'name': 'Attack on Titan',
  'vote_average': 8.684,
  'vote_count': 7610}]

In [26]:
#converting this list in dataframe

pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg,"[10759, 18, 35]",276161,[KR],ko,참교육,An inspector from the Educational Rights Prote...,72.1513,/fMECSPrTmRClSViMsXFYmiYIcWP.jpg,2026-06-05,False,Teach You a Lesson,9.419,788
1,False,/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg,"[37, 18]",299167,[US],en,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,67.3828,/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg,2026-05-15,False,Dutton Ranch,9.175,512
2,False,/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg,"[18, 80]",1396,[US],en,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",147.6765,/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg,2008-01-20,False,Breaking Bad,8.947,18346
3,False,/TGJ34SvYJ2ZgzsOgAaXzSx3o7E.jpg,[18],273240,[US],en,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,91.7782,/tcPc5ZMBO4y2BtCJMe3o2nwZb2B.jpg,2026-05-13,False,Off Campus,8.914,772
4,False,/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg,"[10759, 35, 10765, 18]",259837,[KR],ko,원더풀스,A goofy group of townies stumbles into superpo...,24.6367,/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg,2026-05-15,False,The WONDERfools,8.900,241
5,False,/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg,"[16, 10759, 18, 10765]",209867,[JP],ja,葬送のフリーレン,After the party of heroes defeated the Demon K...,85.9744,/dqZENchTd7lp5zht7BdlqM7RBhD.jpg,2023-09-29,False,Frieren: Beyond Journey's End,8.800,918
6,False,/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg,"[10759, 10751, 18]",85077,[US],en,The Chosen,The life of Christ through the eyes of those w...,74.8496,/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg,2019-04-21,False,The Chosen,8.783,943
7,False,/kU98MbVVgi72wzceyrEbClZmMFe.jpg,"[16, 10759, 10765]",246,[US],en,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",34.2859,/yaGt4GIutpbXHsv48tWceWg6s56.jpg,2005-02-21,False,Avatar: The Last Airbender,8.776,5031
8,False,/wgmikRStgBbrzjxFVe5rhFlpL2R.jpg,[35],64010,[KR],ko,응답하라 1988,Take a nostalgic trip back to the late 1980s t...,16.1474,/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg,2015-11-06,False,Reply 1988,8.800,221
9,False,/a9qlroMOHewiDsUR93PYMVfpbF5.jpg,[18],219246,[KR],ko,폭싹 속았수다,"In Jeju, a spirited girl and a steadfast boy's...",26.3361,/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg,2025-03-07,False,When Life Gives You Tangerines,8.759,565
10,False,/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg,"[16, 10759, 10765]",94605,[US],en,Arcane,Amid the stark discord of twin cities Piltover...,35.5446,/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg,2021-11-06,False,Arcane,8.752,6090
11,False,/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg,"[10759, 35, 16]",37854,[JP],ja,ワンピース,"Years ago, the fearsome Pirate King, Gol D. Ro...",50.2370,/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg,1999-10-20,False,One Piece,8.752,5474
12,False,/iS76c29IrS3lKI2X5CFySguiAWU.jpg,[18],301507,[CA],en,Heated Rivalry,Two of the biggest stars in Major League Hocke...,31.6016,/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg,2025-11-28,False,Heated Rivalry,8.750,570
13,False,/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg,[18],250307,[US],en,The Pitt,The staff of Pittsburgh's Trauma Medical Cente...,90.0029,/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg,2025-01-09,False,The Pitt,8.727,890
14,False,/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg,[18],87108,[US],en,Chernobyl,The true story of one of the worst man-made ca...,37.6323,/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg,2019-05-06,False,Chernobyl,8.722,8143
15,False,/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg,"[16, 10759, 10765, 18]",31911,[JP],ja,鋼の錬金術師 FULLMETAL ALCHEMIST,Disregard for alchemy’s laws ripped half of Ed...,47.3033,/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg,2009-04-05,False,Fullmetal Alchemist: Brotherhood,8.700,2533
16,False,/rfxryDIv8huejujg4JueDJx8zCz.jpg,"[80, 18]",60059,[US],en,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,74.8616,/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg,2015-02-08,False,Better Call Saul,8.711,6739
17,False,/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg,"[18, 35]",259666,[MX],es,Nadie nos va a extrañar,"It's the '90s, and five losers run an illegal ...",41.9727,/5U3WiAz67fJn5gnvFk4zOJAx9Sc.jpg,2024-08-09,False,No One Will Miss Us,8.709,340
18,False,/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg,"[10759, 18]",200709,[KR],ko,약한영웅,"With the aid of unexpected friends, a gifted b...",49.3876,/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg,2022-11-18,False,Weak Hero,8.699,502
19,False,/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg,"[16, 10765, 10759]",1429,[JP],ja,進撃の巨人,"100 years ago, the last remnants of humanity w...",31.3241,/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg,2013-04-07,False,Attack on Titan,8.684,7610

In [27]:
#extracting details

df= pd.DataFrame(response.json()['results'])[['id', 'name', 'original_name' , 'vote_average' ]]

In [28]:
df

,id,name,original_name,vote_average
0,276161,Teach You a Lesson,참교육,9.419
1,299167,Dutton Ranch,Dutton Ranch,9.175
2,1396,Breaking Bad,Breaking Bad,8.947
3,273240,Off Campus,Off Campus,8.914
4,259837,The WONDERfools,원더풀스,8.900
5,209867,Frieren: Beyond Journey's End,葬送のフリーレン,8.800
6,85077,The Chosen,The Chosen,8.783
7,246,Avatar: The Last Airbender,Avatar: The Last Airbender,8.776
8,64010,Reply 1988,응답하라 1988,8.800
9,219246,When Life Gives You Tangerines,폭싹 속았수다,8.759
10,94605,Arcane,Arcane,8.752
11,37854,One Piece,ワンピース,8.752
12,301507,Heated Rivalry,Heated Rivalry,8.750
13,250307,The Pitt,The Pitt,8.727
14,87108,Chernobyl,Chernobyl,8.722
15,31911,Fullmetal Alchemist: Brotherhood,鋼の錬金術師 FULLMETAL ALCHEMIST,8.700
16,60059,Better Call Saul,Better Call Saul,8.711
17,259666,No One Will Miss Us,Nadie nos va a extrañar,8.709
18,200709,Weak Hero,약한영웅,8.699
19,1429,Attack on Titan,進撃の巨人,8.684

In [32]:
all_dfs = []
for i in range (1 ,127):
  # Correctly format the URL to include the page number
  response = requests.get(f'https://api.themoviedb.org/3/tv/top_rated?api_key=40ce6d2d68786e189606e98b6c89eb07&language=en-US&page={i}')
  if response.status_code == 200:
      temp_df = pd.DataFrame(response.json()['results'])[['id', 'name', 'original_name' , 'vote_average' ]]
      all_dfs.append(temp_df) # Append to a list
  else:
      print(f"Error fetching page {i}: {response.status_code}")

# Concatenate all DataFrames in the list after the loop
df = pd.concat(all_dfs, ignore_index=True)
df

          id                name      original_name  vote_average
0     276161  Teach You a Lesson                참교육         9.419
1     299167        Dutton Ranch       Dutton Ranch         9.175
2       1396        Breaking Bad       Breaking Bad         8.947
3     273240          Off Campus         Off Campus         8.914
4     259837     The WONDERfools               원더풀스         8.900
...      ...                 ...                ...           ...
2509  130392   The D'Amelio Show  The D'Amelio Show         5.009
2510   10160         Big Brother        Big Brother         4.846
2511    1871          EastEnders         EastEnders         4.249
2512  126725               Velma              Velma         3.475
2513  224387     Queen Cleopatra    Queen Cleopatra         2.673

[2514 rows x 4 columns]

In [33]:
df.shape

(2514, 4)

In [34]:
df.to_csv('movies.csv')