In [37]:
import pandas as pd

In [38]:
s= pd.Series([10,20,30, 'abc'])
s

0     10
1     20
2     30
3    abc
dtype: object

In [39]:
s.dtype

dtype('O')

In [40]:
s.values

array([10, 20, 30, 'abc'], dtype=object)

In [41]:
s.index

RangeIndex(start=0, stop=4, step=1)

In [42]:
s.name

In [43]:
s.name ="numbers"
s

0     10
1     20
2     30
3    abc
Name: numbers, dtype: object

In [44]:
# indexing

s[0]

10

In [45]:
s[0:2]

0    10
1    20
Name: numbers, dtype: object

In [46]:
#iloc -> location based indexing

s.iloc[3]

'abc'

In [47]:
s.iloc[[1,3,2]]

1     20
3    abc
2     30
Name: numbers, dtype: object

In [48]:
index = ["apple", "banana" , "orange" , "ewewewe"]

In [49]:
s.index = index
s

apple       10
banana      20
orange      30
ewewewe    abc
Name: numbers, dtype: object

In [50]:
s["apple"]

10

In [51]:
s.iloc[3]

'abc'

In [52]:
s.["apple"] #invalid coz iloc is used for numerical indexes only therefore we have another function called loc

SyntaxError: invalid syntax (1880345048.py, line 1)

In [53]:
# loc --> lable based indexing
s.loc["apple"]

10

In [54]:
#in label bassed indexing both start and stop values are included in output

s['apple':'orange']

apple     10
banana    20
orange    30
Name: numbers, dtype: object

In [55]:
#dictonaries

fruit_protien = {
    "Avacado":2.0,
     "Guava":2.6,
    "oranges":1.1,
    "kiwi":0.3

}

In [56]:
s2 = pd.Series(fruit_protien , name ="Protein")
s2

Avacado    2.0
Guava      2.6
oranges    1.1
kiwi       0.3
Name: Protein, dtype: float64

In [57]:
#Conditional Selection

s2>1

Avacado     True
Guava       True
oranges     True
kiwi       False
Name: Protein, dtype: bool

In [58]:
s2[s2>1]

Avacado    2.0
Guava      2.6
oranges    1.1
Name: Protein, dtype: float64

In [59]:
#Logical Operatooes : and or not

s2[(s2>0.5) & (s2 <= 2)]

Avacado    2.0
oranges    1.1
Name: Protein, dtype: float64

In [60]:
s2[(s2>0.5) | (s2 <= 2)]

Avacado    2.0
Guava      2.6
oranges    1.1
kiwi       0.3
Name: Protein, dtype: float64

In [61]:
s2[~(s2>0.5)]

kiwi    0.3
Name: Protein, dtype: float64

In [62]:
#modifying series

s2["Mango"] = 2.8
s2

Avacado    2.0
Guava      2.6
oranges    1.1
kiwi       0.3
Mango      2.8
Name: Protein, dtype: float64

In [63]:

s2["kiwi"] = 1.8
s2

Avacado    2.0
Guava      2.6
oranges    1.1
kiwi       1.8
Mango      2.8
Name: Protein, dtype: float64

In [64]:
#DATAFRAMES

data = {
    "Name": ["Alice" , "Bob" , "Charlie" , "David" , "Alice"],
    "Age": [25,  None, 35, 40 , 25],
    "City": ["New York", "San Francisco", "Chicago", "Chicago", "New York"],
    "salary":[ None ,20000,30000,40000, None]
}

In [65]:
import pandas as pd
df = pd.DataFrame(data)
df

      Name   Age           City   salary
0    Alice  25.0       New York      NaN
1      Bob   NaN  San Francisco  20000.0
2  Charlie  35.0        Chicago  30000.0
3    David  40.0        Chicago  40000.0
4    Alice  25.0       New York      NaN

In [66]:
df.head(2)

    Name   Age           City   salary
0  Alice  25.0       New York      NaN
1    Bob   NaN  San Francisco  20000.0

In [67]:
df.tail(2)

    Name   Age      City   salary
3  David  40.0   Chicago  40000.0
4  Alice  25.0  New York      NaN

In [68]:
#loc and iloc

df.iloc[1:3] #rows and columns

      Name   Age           City   salary
1      Bob   NaN  San Francisco  20000.0
2  Charlie  35.0        Chicago  30000.0

In [69]:
df.loc[1:3 , ["Age" , "City"]]

    Age           City
1   NaN  San Francisco
2  35.0        Chicago
3  40.0        Chicago

In [70]:
 df["Age"]

0    25.0
1     NaN
2    35.0
3    40.0
4    25.0
Name: Age, dtype: float64

In [71]:
df.drop("Age" , axis=1) #if we want a row to be gone axis=0 and for column axis=1

      Name           City   salary
0    Alice       New York      NaN
1      Bob  San Francisco  20000.0
2  Charlie        Chicago  30000.0
3    David        Chicago  40000.0
4    Alice       New York      NaN

In [72]:
df

      Name   Age           City   salary
0    Alice  25.0       New York      NaN
1      Bob   NaN  San Francisco  20000.0
2  Charlie  35.0        Chicago  30000.0
3    David  40.0        Chicago  40000.0
4    Alice  25.0       New York      NaN

In [73]:
#implace = True  if we want to make changes in actual dataframe
#by default implace = False

df.drop ("Age" ,axis=1 , inplace = True)

In [74]:
df.shape

(5, 3)

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   City    5 non-null      object
 2   salary  3 non-null      float64
dtypes: float64(1), object(2)
memory usage: 252.0+ bytes

In [76]:
df.describe()

        salary
count      3.0
mean   30000.0
std    10000.0
min    20000.0
25%    25000.0
50%    30000.0
75%    35000.0
max    40000.0

In [77]:
#Broadcasting
# The 'Age' column was previously dropped from 'df'.
# We are restoring it from the original 'data' dictionary to allow the operation.
df["Age"] = data["Age"]
df["Age"] = df["Age"]+5
df

      Name           City   salary   Age
0    Alice       New York      NaN  30.0
1      Bob  San Francisco  20000.0   NaN
2  Charlie        Chicago  30000.0  40.0
3    David        Chicago  40000.0  45.0
4    Alice       New York      NaN  30.0

In [78]:
#Renamimg columns

df.rename(columns = {"Age": "AAyu"})

      Name           City   salary  AAyu
0    Alice       New York      NaN  30.0
1      Bob  San Francisco  20000.0   NaN
2  Charlie        Chicago  30000.0  40.0
3    David        Chicago  40000.0  45.0
4    Alice       New York      NaN  30.0

In [79]:
df["City"].unique()

array(['New York', 'San Francisco', 'Chicago'], dtype=object)

In [80]:
df["City"].value_counts()

City
New York         2
Chicago          2
San Francisco    1
Name: count, dtype: int64

In [81]:
df["Promoted Salary"] = df["salary"]*10
df

      Name           City   salary   Age  Promoted Salary
0    Alice       New York      NaN  30.0              NaN
1      Bob  San Francisco  20000.0   NaN         200000.0
2  Charlie        Chicago  30000.0  40.0         300000.0
3    David        Chicago  40000.0  45.0         400000.0
4    Alice       New York      NaN  30.0              NaN

In [82]:
#data cleaning


df.isnull().sum()

Name               0
City               0
salary             2
Age                1
Promoted Salary    2
dtype: int64

In [83]:
df.dropna() #removes all the columns with null vaules the original dataset remains untouched

      Name     City   salary   Age  Promoted Salary
2  Charlie  Chicago  30000.0  40.0         300000.0
3    David  Chicago  40000.0  45.0         400000.0

In [84]:
df.dropna(how = "any") #any row having null values

      Name     City   salary   Age  Promoted Salary
2  Charlie  Chicago  30000.0  40.0         300000.0
3    David  Chicago  40000.0  45.0         400000.0

In [85]:
df.dropna(how = "all") #if all the rows have null values

      Name           City   salary   Age  Promoted Salary
0    Alice       New York      NaN  30.0              NaN
1      Bob  San Francisco  20000.0   NaN         200000.0
2  Charlie        Chicago  30000.0  40.0         300000.0
3    David        Chicago  40000.0  45.0         400000.0
4    Alice       New York      NaN  30.0              NaN

In [86]:
#fillna --> to fill missing values

df.fillna(0)

      Name           City   salary   Age  Promoted Salary
0    Alice       New York      0.0  30.0              0.0
1      Bob  San Francisco  20000.0   0.0         200000.0
2  Charlie        Chicago  30000.0  40.0         300000.0
3    David        Chicago  40000.0  45.0         400000.0
4    Alice       New York      0.0  30.0              0.0

In [87]:
df["Age"].fillna(df["Age"].mean())

0    30.00
1    36.25
2    40.00
3    45.00
4    30.00
Name: Age, dtype: float64

In [88]:
df["salary"].fillna(df["salary"].median())

0    30000.0
1    20000.0
2    30000.0
3    40000.0
4    30000.0
Name: salary, dtype: float64

In [89]:
df["Age"].fillna(method='ffill')

/tmp/ipykernel_2126/1444085321.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method='ffill')

0    30.0
1    30.0
2    40.0
3    45.0
4    30.0
Name: Age, dtype: float64

In [90]:
df["Age"].fillna(method='bfill')

/tmp/ipykernel_2126/2665262052.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Age"].fillna(method='bfill')

0    30.0
1    40.0
2    40.0
3    45.0
4    30.0
Name: Age, dtype: float64

In [91]:
df["Name"].replace("Charlie", "Rose")

0    Alice
1      Bob
2     Rose
3    David
4    Alice
Name: Name, dtype: object

In [92]:
df["Name"]= df["Name"].replace("Charlie", "Rose")
df

    Name           City   salary   Age  Promoted Salary
0  Alice       New York      NaN  30.0              NaN
1    Bob  San Francisco  20000.0   NaN         200000.0
2   Rose        Chicago  30000.0  40.0         300000.0
3  David        Chicago  40000.0  45.0         400000.0
4  Alice       New York      NaN  30.0              NaN

In [93]:
#Duplicates --> to show repeated or duplicated values

df_dup = df[df.duplicated()]
df_dup

    Name      City  salary   Age  Promoted Salary
4  Alice  New York     NaN  30.0              NaN

In [94]:
df_dup = df[df.duplicated(keep ="last")] #marks first as duPlicate
df_dup

    Name      City  salary   Age  Promoted Salary
0  Alice  New York     NaN  30.0              NaN

In [95]:
df_dup = df[df.duplicated(keep = "first")] #BY DEFAULT marks last as duplicate
df_dup

    Name      City  salary   Age  Promoted Salary
4  Alice  New York     NaN  30.0              NaN

In [96]:
#invalid salaries

#lambda --> python

df["Promoted Salary"] = df["Promoted Salary"].apply(lambda x: x/10 if x>30000 else x)
df

    Name           City   salary   Age  Promoted Salary
0  Alice       New York      NaN  30.0              NaN
1    Bob  San Francisco  20000.0   NaN          20000.0
2   Rose        Chicago  30000.0  40.0          30000.0
3  David        Chicago  40000.0  45.0          40000.0
4  Alice       New York      NaN  30.0              NaN

In [97]:
#spliting the string

name= "alice_mishra"
df[["first_name" , "last_name"]] =  df["name"].str.split("_")

#split sthe string from wherever there is _

KeyError: 'name'

In [100]:
#apply and lambda
def multiplying_age(x):
  return x*2

df["Age"] = df["Age"].apply(multiplying_age)
df

    Name           City   salary   Age  Promoted Salary
0  Alice       New York      NaN  60.0              NaN
1    Bob  San Francisco  20000.0   NaN          20000.0
2   Rose        Chicago  30000.0  80.0          30000.0
3  David        Chicago  40000.0  90.0          40000.0
4  Alice       New York      NaN  60.0              NaN

In [101]:
df["Age"] = df["Age"].apply(lambda x: x/2)
df

    Name           City   salary   Age  Promoted Salary
0  Alice       New York      NaN  30.0              NaN
1    Bob  San Francisco  20000.0   NaN          20000.0
2   Rose        Chicago  30000.0  40.0          30000.0
3  David        Chicago  40000.0  45.0          40000.0
4  Alice       New York      NaN  30.0              NaN

In [102]:
#Joins --> left right outer inner
import pandas as pd
department_info = {

                    "Dept" : ["HR", "IT", "Finance"],
                    "Location": ["NewYork", "San Francisco", "Chicago"],
                    "Manager": ["Alice", "Bob", "Charlie"]
                    }

df2 = pd.DataFrame(department_info)
df2

      Dept       Location  Manager
0       HR        NewYork    Alice
1       IT  San Francisco      Bob
2  Finance        Chicago  Charlie

In [103]:
#concat

pd.concat([df , df2])  #row wise concatanation
#pehle df ka sara data usme dept loc manager nhitha to woh NaN
#fir df2 usme  name city salary age aur p_sal nhi thi to NaN

,Name,City,salary,Age,Promoted Salary,Dept,Location,Manager
0,Alice,New York,NaN,30.0,NaN,NaN,NaN,NaN
1,Bob,San Francisco,20000.0,NaN,20000.0,NaN,NaN,NaN
2,Rose,Chicago,30000.0,40.0,30000.0,NaN,NaN,NaN
3,David,Chicago,40000.0,45.0,40000.0,NaN,NaN,NaN
4,Alice,New York,NaN,30.0,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,HR,NewYork,Alice
1,NaN,NaN,NaN,NaN,NaN,IT,San Francisco,Bob
2,NaN,NaN,NaN,NaN,NaN,Finance,Chicago,Charlie

In [104]:
pd.concat([df , df2], axis =1)

# column wise concatanation df k sare cols + df2 k sare cols

,Name,City,salary,Age,Promoted Salary,Dept,Location,Manager
0,Alice,New York,NaN,30.0,NaN,HR,NewYork,Alice
1,Bob,San Francisco,20000.0,NaN,20000.0,IT,San Francisco,Bob
2,Rose,Chicago,30000.0,40.0,30000.0,Finance,Chicago,Charlie
3,David,Chicago,40000.0,45.0,40000.0,NaN,NaN,NaN
4,Alice,New York,NaN,30.0,NaN,NaN,NaN,NaN

In [ ]:
 #merge when 2 colums are repeated

pd.merge(df , df2 , on = "Dept")

In [ ]:
#Importing file

data = pd.read_csv("path of dataset from file explorer")

In [ ]:
data.head()#to get first some rowa

In [ ]:
data.shape # to get shape

In [ ]:
data.info #to get information abot data

In [ ]:
data['date'] = pd.to_datetime(data['date']) #to convert into datetime format

In [ ]:
data.info()