In [ ]:
import pandas as pd

In [ ]:

df = pd.read_csv('aug_train.csv')
df

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16.0,0.0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135.0,0.0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253.0,0.0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69.0,0.0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
279514,225858,Male,59,1,28.0,1,1-2 Year,No,97917.0,26.0,235.0,0.0
279515,333884,Male,44,1,11.0,1,1-2 Year,No,44823.0,122.0,122.0,0.0
279516,283804,Female,66,1,28.0,1,1-2 Year,No,39743.0,122.0,161.0,0.0
279517,433868,Male,23,1,30.0,1,< 1 Year,No,31634.0,152.0,166.0,0.0
279518,85865,Male,23,1,21.0,1,NaN,NaN,NaN,NaN,NaN,NaN

# **OPENING CSV FILE FROM URL**

In [ ]:
#code snipent - server s csv file ka data load krna ho

import requests
from io import StringIO

# Replace this with the actual URL of your CSV file.
# Using a sample public CSV URL for demonstration.
url = "https://raw.githubusercontent.com/plotly/datasets/master/iris-data.csv"

headers = {"User-Agent": "Mozilla/S.0 (Macintosh;Intel Mac Os X 10.14;)Gecmo/20100101 Firefox/66.0"}
req = requests.get(url,headers=headers)
data = StringIO(req.text)

df_from_url = pd.read_csv(data)
display(df_from_url.head())

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

#**sep parameter**

In [ ]:
pd.read_csv('aug_train.csv' , sep=',') # default value is comma  we can use \t fortab  seperation

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16.0,0.0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135.0,0.0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253.0,0.0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69.0,0.0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
298148,392722,Female,36,1,3.0,0,1-2 Year,Yes,33002.0,154.0,236.0,1.0
298149,232155,Male,24,1,41.0,1,< 1 Year,No,41469.0,152.0,208.0,0.0
298150,32645,Male,52,1,28.0,0,> 2 Years,Yes,64254.0,26.0,120.0,0.0
298151,87092,Female,39,1,11.0,0,1-2 Year,Yes,2630.0,156.0,230.0,0.0
298152,146346,Female,55,1,24.0,0,1-2 Year,Yes,28744.0,14.0,NaN,NaN

In [ ]:
pd.read_csv('aug_train.csv' , sep=',' , names =['S.no']) #like this we can name the column of the dataset if not given

/tmp/ipykernel_896/3619208082.py:1: DtypeWarning: Columns (0,2,3,4,5,8,9,10,11) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('aug_train.csv' , sep=',' , names =['S.no'])

                                                                                                                                             S.no
id     Gender Age Driving_License Region_Code Previously_Insured Vehicle_Age Vehicle_Damage Annual_Premium Policy_Sales_Channel Vintage  Response
167647 Male   22  1               7.0         1                  < 1 Year    No             2630.0         152.0                16              0
17163  Male   42  1               28.0        0                  1-2 Year    Yes            43327.0        26.0                 135             0
32023  Female 66  1               33.0        0                  1-2 Year    Yes            35841.0        124.0                253             0
87447  Female 22  1               33.0        0                  < 1 Year    No             27645.0        152.0                69              0
...                                                                                                                                           ...
164549 Male   24  1               15.0        0                  < 1 Year    Yes            23938.0        152.0                105             0
247064 Male   27  1               28.0        1                  < 1 Year    No             336395.0       152.0                144             0
165293 Male   45  1               28.0        0                  1-2 Year    Yes            40443.0        26.0                 187             0
383241 Female 28  1               28.0        1                  < 1 Year    No             25380.0        152.0                208             0
401019 Female 29  1               18.0        1                  < 1 Year    No             30396.0        152.0                104             0

[382155 rows x 1 columns]

# **Index col parameter**

In [ ]:
pd.read_csv('aug_train.csv') #here we have two indexes first starting from 0 and another as id
#we can convert the id as index column as

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382149,164549,Male,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
382150,247064,Male,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
382151,165293,Male,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
382152,383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
382153,401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

In [ ]:
pd.read_csv('aug_train.csv', index_col='id')

,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
id,,,,,,,,,,,
167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...
164549,Male,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
247064,Male,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
165293,Male,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

#**HEADERPARAMETER**

In [ ]:
pd.read_csv('aug_train.csv' , header =0)  # when columns are treated as rows not in this case but sometimes it happens ki the 0 can be the cols names but is in the form of row
#to make it a column name we use this parameter

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382149,164549,Male,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
382150,247064,Male,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
382151,165293,Male,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
382152,383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
382153,401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

#**USE COLS PARAMETER**

In [ ]:
pd.read_csv('aug_train.csv' , usecols=['id' ,'Gender', 'Age']) #we can print or decide which column can be printed and which not

            id  Gender  Age
0       167647    Male   22
1        17163    Male   42
2        32023  Female   66
3        87447  Female   22
4       501933    Male   28
...        ...     ...  ...
382149  164549    Male   24
382150  247064    Male   27
382151  165293    Male   45
382152  383241  Female   28
382153  401019  Female   29

[382154 rows x 3 columns]

#**squeeze parameters**

In [ ]:
pd.read_csv('aug_train.csv' , usecols =['Gender'])['Gender']

0           Male
1           Male
2         Female
3         Female
4           Male
           ...
382149      Male
382150      Male
382151      Male
382152    Female
382153    Female
Name: Gender, Length: 382154, dtype: object

#**skiprows/nrowa parameter**

In [ ]:
pd.read_csv('aug_train.csv' ,skiprows=[0,4]) #skips the mentioned rows

,167647,Male,22,1,7.0,1.1,< 1 Year,No,2630.0,152.0,16,0
0,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
1,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
2,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
3,295775,Female,25,1,25.0,1,< 1 Year,No,27954.0,152.0,23,0
4,71711,Male,51,1,8.0,0,1-2 Year,Yes,2630.0,26.0,209,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382147,164549,Male,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
382148,247064,Male,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
382149,165293,Male,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
382150,383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
382151,401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

In [ ]:
pd.read_csv('aug_train.csv' ,nrows=100) #restricts the number of rows being printed

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
95,277104,Female,40,1,41.0,0,1-2 Year,Yes,16941.0,157.0,102,0
96,107785,Female,23,1,3.0,0,< 1 Year,No,2630.0,160.0,281,0
97,259427,Female,24,1,28.0,1,< 1 Year,No,37444.0,153.0,237,0
98,6420,Male,22,1,10.0,1,< 1 Year,No,23937.0,152.0,166,0
99,306816,Female,69,1,43.0,1,1-2 Year,No,2630.0,160.0,155,0

# **encoding parameter**

In [ ]:
pd.read_csv('aug_train.csv' , encoding ='latin-1') #sometimsit may happen ki encoding of the charcters are not in UTF 8 to specify that we use encoding parameter

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382149,164549,Male,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
382150,247064,Male,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
382151,165293,Male,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
382152,383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
382153,401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

#**skip bad lines**

In [ ]:
pd.read_csv('aug_train.csv' , on_bad_lines='skip') #skips the rows with multiple values

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382149,164549,Male,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
382150,247064,Male,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
382151,165293,Male,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
382152,383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
382153,401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

# **dtypes parameter**

In [ ]:
pd.read_csv('aug_train.csv', dtype={'Annual_Premium': int}) #the datatype of the Annual_Premium has been changed to integer

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382149,164549,Male,24,1,15.0,0,< 1 Year,Yes,23938,152.0,105,0
382150,247064,Male,27,1,28.0,1,< 1 Year,No,336395,152.0,144,0
382151,165293,Male,45,1,28.0,0,1-2 Year,Yes,40443,26.0,187,0
382152,383241,Female,28,1,28.0,1,< 1 Year,No,25380,152.0,208,0
382153,401019,Female,29,1,18.0,1,< 1 Year,No,30396,152.0,104,0

# **converters**

In [ ]:
# Load the CSV file
df = pd.read_csv('aug_train.csv')

# Rename the 'Driving_License' column to 'DL'
df = df.rename(columns={'Driving_License': 'DL'})

# Display the DataFrame to see the change
display(df.head())

,id,Gender,Age,DL,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,Male,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,Male,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,Male,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0

#**na_values parameter**

In [ ]:
pd.read_csv('aug_train.csv', na_values = ['Male']) # kahi bhi agr placeholders hain such as a hiphan or perctage there we use na values

,id,Gender,Age,Driving_License,Region_Code,Previously_Insured,Vehicle_Age,Vehicle_Damage,Annual_Premium,Policy_Sales_Channel,Vintage,Response
0,167647,NaN,22,1,7.0,1,< 1 Year,No,2630.0,152.0,16,0
1,17163,NaN,42,1,28.0,0,1-2 Year,Yes,43327.0,26.0,135,0
2,32023,Female,66,1,33.0,0,1-2 Year,Yes,35841.0,124.0,253,0
3,87447,Female,22,1,33.0,0,< 1 Year,No,27645.0,152.0,69,0
4,501933,NaN,28,1,46.0,1,< 1 Year,No,29023.0,152.0,211,0
...,...,...,...,...,...,...,...,...,...,...,...,...
382149,164549,NaN,24,1,15.0,0,< 1 Year,Yes,23938.0,152.0,105,0
382150,247064,NaN,27,1,28.0,1,< 1 Year,No,336395.0,152.0,144,0
382151,165293,NaN,45,1,28.0,0,1-2 Year,Yes,40443.0,26.0,187,0
382152,383241,Female,28,1,28.0,1,< 1 Year,No,25380.0,152.0,208,0
382153,401019,Female,29,1,18.0,1,< 1 Year,No,30396.0,152.0,104,0

#**loading a huge dataset in chunks**

In [ ]:
dfs= pd.read_csv('aug_train.csv', chunksize = 5000)

In [ ]:
for chunks in dfs:
  print(chunks.shape)

(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(5000, 12)
(2154, 12)